spring.application.name=learn-springBoot
logging.level.org.springframework=trace
currency-service.url=https://default.dev.in28minutes.com
currency-service.username=devName
currency-service.key=devKey
