spring.application.name=learn-springBoot
spring.profiles.active=dev
currency-service.url=https://default.in28minutes.com
currency-service.username=defaultname
currency-service.key=defaultkey
management.endpoints.web.exposure.include=*